#!/bin/bash

ssh root@46.101.115.48 "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
cat ~/.ssh/id_rsa.pub | ssh root@46.101.115.48 'cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys'
ssh root@46.101.115.48 << EOF
cd /root/test-backend
git pull origin head
npm install --production
pm2 restart all
exit
EOF
